#!/usr/bin/env python3
# ============================================================================
# Copyright (c) 2026 Supratim Sanyal of SANYALnet Labs.
# Proprietary rights reserved except as expressly licensed herein.
#
# DECnet-IV-Linux
# This file is governed by the SANYALnet Labs Non-Commercial License in the
# root LICENSE file. Non-Commercial use is permitted; Commercial Use and use
# for AI/ML model training are prohibited unless separately authorized.
#
# Attribution is required: "Based on original work by Supratim Sanyal of
# SANYALnet Labs." See LICENSE for full terms, warranty disclaimer, termination,
# patent, trademark, and governing-law provisions.
# ============================================================================

from __future__ import annotations

import pathlib
import sys

BODY = "QCOCAL-DECNET-HTTP-PASS\n"
CONTENT_LENGTH = len(BODY.encode("ascii"))

PROGRAM = f"""$! Ephemeral DECnet HTTP zero-object generated by DECnet-IV-Linux
$ set noon
$ open/read/write net sys$net
$ read/end=done net request
$ cr = f$char(13)
$ lf = f$char(10)
$ body = "QCOCAL-DECNET-HTTP-PASS" + lf
$ reply = "HTTP/1.0 200 OK" + cr + lf + -
          "Content-Length: {CONTENT_LENGTH}" + cr + lf + -
          "Content-Type: text/plain" + cr + lf + -
          "Connection: close" + cr + lf + cr + lf + body
$ write net reply
$done:
$ close net
$ exit
"""


def validate(program: str) -> None:
    required = (
        "$ open/read/write net sys$net",
        "$ read/end=done net request",
        f'"Content-Length: {CONTENT_LENGTH}"',
        "QCOCAL-DECNET-HTTP-PASS",
        "$ write net reply",
        "$ close net",
    )
    if not all(item in program for item in required):
        raise SystemExit("make-http-com: invalid generated program")
    if "#" in program:
        raise SystemExit("make-http-com: non-DCL header leaked into generated program")


def main() -> int:
    validate(PROGRAM)
    if len(sys.argv) == 2 and sys.argv[1] == "--selftest":
        print("make-http-com selftest passed")
        return 0
    if len(sys.argv) != 2:
        raise SystemExit(f"usage: {sys.argv[0]} OUTPUT.COM | --selftest")
    path = pathlib.Path(sys.argv[1])
    path.write_text(PROGRAM, encoding="ascii", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
