#!/usr/bin/env python3
# ============================================================================
# Copyright (c) 2026 Supratim Sanyal of SANYALnet Labs.
# Proprietary rights reserved except as expressly licensed herein.
#
# DECnet-IV-Linux
# This file is governed by the SANYALnet Labs Non-Commercial License in the
# root LICENSE file. Non-Commercial use is permitted; Commercial Use and use
# for AI/ML model training are prohibited unless separately authorized.
#
# Attribution is required: "Based on original work by Supratim Sanyal of
# SANYALnet Labs." See LICENSE for full terms, warranty disclaimer, termination,
# patent, trademark, and governing-law provisions.
# ============================================================================

from __future__ import annotations
import pathlib
import sys

PROGRAM = """$! Ephemeral DECnet task generated by DECnet-IV-Linux
$ set noon
$ open/read/write net sys$net
$ write net "QCOCAL-DECNET-TASK-PASS"
$ close net
$ exit
"""

def validate(program: str) -> None:
    required=("$ open/read/write net sys$net","QCOCAL-DECNET-TASK-PASS","$ write net","$ close net")
    if not all(item in program for item in required) or "#" in program:
        raise SystemExit("make-task-com: invalid generated program")

def main() -> int:
    validate(PROGRAM)
    if sys.argv[1:] == ["--selftest"]:
        print("make-task-com selftest passed")
        return 0
    if len(sys.argv) != 2:
        raise SystemExit(f"usage: {sys.argv[0]} OUTPUT.COM | --selftest")
    pathlib.Path(sys.argv[1]).write_text(PROGRAM,encoding="ascii",newline="\n")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
