PACKAGE_NAME="decnet-iv"
PACKAGE_VERSION="0.1.0"

BUILT_MODULE_NAME[0]="decnet_iv"
BUILT_MODULE_LOCATION[0]="kernel/decnet"
DEST_MODULE_LOCATION[0]="/extra"

MAKE[0]="make -C kernel/decnet KDIR=/lib/modules/${kernelver}/build"
CLEAN="make -C kernel/decnet KDIR=/lib/modules/${kernelver}/build clean"

AUTOINSTALL="yes"
